#!/bin/sh

case `uname -s` in
    Darwin)
        exec /Applications/Emacs.app/Contents/MacOS/bin/emacsclient --alternate-editor="" "$@"
        ;;
    Linux)
        emacsclient --alternate-editor="" "$@"
        ;;
    *)
        echo "Unknown platform, exiting!!"
        exit 1
        ;;
esac
